Update cd-pipelines.yml for Azure Pipelines

diff --git a/deploy/pipelines/cd-pipelines.yml b/deploy/pipelines/cd-pipelines.yml
--- a/deploy/pipelines/cd-pipelines.yml
+++ b/deploy/pipelines/cd-pipelines.yml
@@ -30,27 +30,27 @@ stages:
   
 - stage: CI_Stage
   
-  jobs:
-  - job: RunUnitTests
-    displayName: 'Run_Unit_Tests'
-    pool:
-      vmImage: 'windows-latest'
-    steps:
-    - task: NuGetAuthenticate@1
-      displayName: 'Authenticate to NuGet'
+  # jobs:
+  # - job: RunUnitTests
+  #   displayName: 'Run_Unit_Tests'
+  #   pool:
+  #     vmImage: 'windows-latest'
+  #   steps:
+  #   - task: NuGetAuthenticate@1
+  #     displayName: 'Authenticate to NuGet'
 
-    - task: DotNetCoreCLI@2
-      displayName: 'Run Unit Tests'
-      inputs:
-        command: 'test'
-        projects: '**/*Tests/*.csproj'
-        arguments: '--configuration $(buildConfiguration)'
+  #   - task: DotNetCoreCLI@2
+  #     displayName: 'Run Unit Tests'
+  #     inputs:
+  #       command: 'test'
+  #       projects: '**/*Tests/*.csproj'
+  #       arguments: '--configuration $(buildConfiguration)'
 
-    - task: PublishTestResults@2
-      displayName: 'Publish Test Results'
-      inputs:
-        testResultsFormat: 'VSTest'
-        testResultsFiles: '**/TestResults/*.trx'
+  #   - task: PublishTestResults@2
+  #     displayName: 'Publish Test Results'
+  #     inputs:
+  #       testResultsFormat: 'VSTest'
+  #       testResultsFiles: '**/TestResults/*.trx'
 
 
   # - job: Agent_CI_Job
@@ -85,90 +85,90 @@ stages:
   #       artifactName: 'cloudpillar'
   #       publishLocation: 'Container'  
 
-#   - ${{each item in parameters.services}}:
-#       - job: '${{ item }}_CI_Job'
-#         pool:
-#           vmImage: ubuntu-latest
-#         steps:
-#         - task: NuGetAuthenticate@1
-#           displayName: 'Authenticate to NuGet'
+  - ${{each item in parameters.services}}:
+      - job: '${{ item }}_CI_Job'
+        pool:
+          vmImage: ubuntu-latest
+        steps:
+        - task: NuGetAuthenticate@1
+          displayName: 'Authenticate to NuGet'
           
-#         - task: Docker@2
-#           displayName: '${{ item }} Dockerize'
-#           inputs:
-#             repository: 'cloudpillar${{ lower(item) }}service'
-#             containerRegistry: 'CP ${{ parameters.env }} docker registry'
-#             command: 'build'
-#             Dockerfile: './src/backend/infra/build/Dockerfile'
-#             buildContext: src
-#             tags: '$(imagetag)'
-#             arguments: '--build-arg FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN) --build-arg DLL=Backend.${{ item }}'        
+        - task: Docker@2
+          displayName: '${{ item }} Dockerize'
+          inputs:
+            repository: 'cloudpillar${{ lower(item) }}service'
+            containerRegistry: 'CP ${{ parameters.env }} docker registry'
+            command: 'build'
+            Dockerfile: './src/backend/infra/build/Dockerfile'
+            buildContext: src
+            tags: '$(imagetag)'
+            arguments: '--build-arg FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN) --build-arg DLL=Backend.${{ item }}'        
             
-#         - script: |
-#             SCAN_RESULT=$(docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL cp${{ parameters.env }}acr.azurecr.io/cloudpillar${{ lower(item) }}service:$(imagetag))
-#             echo "$SCAN_RESULT" 
-#             if [[ $SCAN_RESULT == *"CRITICAL"* && "$SCAN_RESULT" != *"CRITICAL: 0"* ]]; then
-#               echo "Critical vulnerabilities found. Failing the pipeline."
-#               exit 1  # This will cause the pipeline to fail
-#             fi
-#           displayName: '${{ item }} Security Scan'
+        - script: |
+            SCAN_RESULT=$(docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL cp${{ parameters.env }}acr.azurecr.io/cloudpillar${{ lower(item) }}service:$(imagetag))
+            echo "$SCAN_RESULT" 
+            if [[ $SCAN_RESULT == *"CRITICAL"* && "$SCAN_RESULT" != *"CRITICAL: 0"* ]]; then
+              echo "Critical vulnerabilities found. Failing the pipeline."
+              exit 1  # This will cause the pipeline to fail
+            fi
+          displayName: '${{ item }} Security Scan'
 
-#         - task: Docker@2
-#           displayName: '${{ item }} Docker Push'
-#           inputs:
-#             command: 'push' 
-#             repository: 'cloudpillar${{ lower(item) }}service'
-#             containerRegistry: 'cp ${{ parameters.env }} docker registry'
-#             tags: '$(imagetag)'
+        - task: Docker@2
+          displayName: '${{ item }} Docker Push'
+          inputs:
+            command: 'push' 
+            repository: 'cloudpillar${{ lower(item) }}service'
+            containerRegistry: 'cp ${{ parameters.env }} docker registry'
+            tags: '$(imagetag)'
 
 
-# - stage: CD_Stage
-#   jobs:  
-#   - job: Start_VM_Job
-#     pool:
-#       vmImage: ubuntu-latest
-#     steps:
-#     - checkout: none
-#     - task: AzureCLI@1
-#       displayName: 'Start VM'
-#       inputs:
-#         azureSubscription: 'CloudPillar ${{ parameters.env }}'
-#         scriptLocation: inlineScript
-#         inlineScript: |
-#           az vm start -g cp-ms-${{ parameters.env }}-rg -n aks-${{ parameters.env }}-vm
+- stage: CD_Stage
+  jobs:  
+  - job: Start_VM_Job
+    pool:
+      vmImage: ubuntu-latest
+    steps:
+    - checkout: none
+    - task: AzureCLI@1
+      displayName: 'Start VM'
+      inputs:
+        azureSubscription: 'CloudPillar ${{ parameters.env }}'
+        scriptLocation: inlineScript
+        inlineScript: |
+          az vm start -g cp-ms-${{ parameters.env }}-rg -n aks-${{ parameters.env }}-vm
           
-#   - job: CD_Job
-#     dependsOn: Start_VM_Job
-#     pool:
-#       name: CloudPillar-Pool
-#       demands:
-#       - agent.name -equals cpaks-${{ parameters.env }}-vm-agent
-#     condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
-#     steps:
-#     - task: HelmDeploy@0
-#       inputs:
-#         connectionType: 'Azure Resource Manager'
-#         azureSubscription: CloudPillar ${{ parameters.env }}
-#         azureResourceGroup: 'cp-ms-${{ parameters.env }}-rg'
-#         kubernetesCluster: 'cp-${{ parameters.env }}-aks'
-#         command: 'upgrade'
-#         chartType: 'FilePath'
-#         chartPath: 'deploy/backend/'
-#         releaseName: 'cloudpillarback'
-#         overrideValues: 'image.tag=$(imagetag)'
-#         valueFile: 'deploy/backend/environments/values-${{ parameters.env }}.yaml'
-#         arguments: '--debug --timeout 5m0s'
+  - job: CD_Job
+    dependsOn: Start_VM_Job
+    pool:
+      name: CloudPillar-Pool
+      demands:
+      - agent.name -equals cpaks-${{ parameters.env }}-vm-agent
+    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
+    steps:
+    - task: HelmDeploy@0
+      inputs:
+        connectionType: 'Azure Resource Manager'
+        azureSubscription: CloudPillar ${{ parameters.env }}
+        azureResourceGroup: 'cp-ms-${{ parameters.env }}-rg'
+        kubernetesCluster: 'cp-${{ parameters.env }}-aks'
+        command: 'upgrade'
+        chartType: 'FilePath'
+        chartPath: 'deploy/backend/'
+        releaseName: 'cloudpillarback'
+        overrideValues: 'image.tag=$(imagetag)'
+        valueFile: 'deploy/backend/environments/values-${{ parameters.env }}.yaml'
+        arguments: '--debug --timeout 5m0s'
         
-#   - job: Stop_VM_Job
-#     dependsOn: CD_Job
-#     pool:
-#       vmImage: ubuntu-latest
-#     steps:
-#     - checkout: none
-#     - task: AzureCLI@1
-#       displayName: 'Stop VM'
-#       inputs:
-#         azureSubscription: 'CloudPillar ${{ parameters.env }}'
-#         scriptLocation: inlineScript
-#         inlineScript: |
-#           az vm deallocate -g cp-ms-${{ parameters.env }}-rg -n aks-${{ parameters.env }}-vm
+  - job: Stop_VM_Job
+    dependsOn: CD_Job
+    pool:
+      vmImage: ubuntu-latest
+    steps:
+    - checkout: none
+    - task: AzureCLI@1
+      displayName: 'Stop VM'
+      inputs:
+        azureSubscription: 'CloudPillar ${{ parameters.env }}'
+        scriptLocation: inlineScript
+        inlineScript: |
+          az vm deallocate -g cp-ms-${{ parameters.env }}-rg -n aks-${{ parameters.env }}-vm
