fix

diff --git a/deploy/pipelines/cd-pipelines.yml b/deploy/pipelines/cd-pipelines.yml
--- a/deploy/pipelines/cd-pipelines.yml
+++ b/deploy/pipelines/cd-pipelines.yml
@@ -105,8 +105,13 @@ stages:
             arguments: '--build-arg FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN) --build-arg DLL=Backend.${{ item }}'        
             
         - script: |
-            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:0.45.1 image --severity HIGH,CRITICAL cp${{ parameters.env }}acr.azurecr.io/cloudpillar${{ lower(item) }}service:$(imagetag)
-          displayName: '${{ item }} Security Scan'        
+            SCAN_RESULT=$(docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL cp${{ parameters.env }}acr.azurecr.io/cloudpillar${{ lower(item) }}service:$(imagetag))
+            echo "$SCAN_RESULT" 
+            if [[ $SCAN_RESULT == *"CRITICAL"* ]]; then
+              echo "Critical vulnerabilities found. Failing the pipeline."
+              exit 1  # This will cause the pipeline to fail
+            fi
+          displayName: '${{ item }} Security Scan'
 
         - task: Docker@2
           displayName: '${{ item }} Docker Push'
