try

diff --git a/deploy/pipelines/ci-cd-pipeline.yml b/deploy/pipelines/ci-cd-pipeline.yml
--- a/deploy/pipelines/ci-cd-pipeline.yml
+++ b/deploy/pipelines/ci-cd-pipeline.yml
@@ -11,6 +11,9 @@ parameters:
   - dev
   - stg
   - prd 
+- name: isCD
+  type: boolean
+  default: false
 
 trigger:
 - none
@@ -19,6 +22,27 @@ trigger:
 stages:  
 - stage: CI_Stage  
   jobs:
+  - job: RunUnitTests
+    displayName: 'Run_Unit_Tests'
+    pool:
+      vmImage: 'windows-latest'
+    steps:
+    - task: NuGetAuthenticate@1
+      displayName: 'Authenticate to NuGet'
+
+    - task: DotNetCoreCLI@2
+      displayName: 'Run Unit Tests'
+      inputs:
+        command: 'test'
+        projects: '**/*Tests/*.csproj'
+        arguments: '--configuration $(buildConfiguration)'
+
+    - task: PublishTestResults@2
+      displayName: 'Publish Test Results'
+      inputs:
+        testResultsFormat: 'VSTest'
+        testResultsFiles: '**/TestResults/*.trx'
+
   - job: Agent_CI_Job
     pool:
       vmImage: ubuntu-latest
@@ -67,7 +91,16 @@ stages:
           Dockerfile: './src/backend/infra/build/Dockerfile'
           buildContext: src
           tags: '$(imagetag)'
-          arguments: '--build-arg FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN) --build-arg DLL=Backend.${{ item }}'
+          arguments: '--build-arg FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN) --build-arg DLL=Backend.${{ item }}'        
+            
+      - script: |
+          SCAN_RESULT=$(docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL cp${{ parameters.env }}acr.azurecr.io/cloudpillar${{ lower(item) }}service:$(imagetag))
+          echo "$SCAN_RESULT" 
+          if [[ $SCAN_RESULT == *"CRITICAL"* && "$SCAN_RESULT" != *"CRITICAL: 0"* ]]; then
+            echo "Critical vulnerabilities found. Failing the pipeline."
+            exit 1  # This will cause the pipeline to fail
+          fi
+        displayName: '${{ item }} Security Scan'
 
       - task: Docker@2
         displayName: '${{ item }} Docker Push'
@@ -81,6 +114,7 @@ stages:
 - stage: CD_Stage
   jobs:  
   - job: Start_VM_Job
+    condition: eq(parameters.isCD, 'true')
     pool:
       vmImage: ubuntu-latest
     steps:
